In [1]:
string1 = 'bangalore'; #single character or single word for single quotes
string2 = "when there are spaces";
string3 = '''he said that,"he's a bad guy"''';
print(string3)

he said that,"he's a bad guy"


In [2]:
import math as m
square = m.sqrt(625)
square

25.0

In [3]:
from math import *
square = sqrt(625)
square

25.0

In [4]:
lst = [1,2,3,4,5,6]
lst.append([7,8])
print(lst)
lst[6]

[1, 2, 3, 4, 5, 6, [7, 8]]


[7, 8]

In [5]:
lst = [1,2,3,4,5,6]
lst.extend([7,8])
print(lst)
lst[6]

[1, 2, 3, 4, 5, 6, 7, 8]


7

In [6]:
for i in range(1,11):
    print(17*i)

17
34
51
68
85
102
119
136
153
170


In [7]:
lst = list(range(17,171,17))
lst

[17, 34, 51, 68, 85, 102, 119, 136, 153, 170]

In [8]:
list('name')

['n', 'a', 'm', 'e']

In [9]:
for i in range(1,11):
    j = 1/i
    print('inverse of',i,'is',j)     #comma adds space in string while + will not

inverse of 1 is 1.0
inverse of 2 is 0.5
inverse of 3 is 0.3333333333333333
inverse of 4 is 0.25
inverse of 5 is 0.2
inverse of 6 is 0.16666666666666666
inverse of 7 is 0.14285714285714285
inverse of 8 is 0.125
inverse of 9 is 0.1111111111111111
inverse of 10 is 0.1


In [10]:
for i in range(1,11):
    j = 1/i
    print('inverse of {} is {}'.format(i,j))

inverse of 1 is 1.0
inverse of 2 is 0.5
inverse of 3 is 0.3333333333333333
inverse of 4 is 0.25
inverse of 5 is 0.2
inverse of 6 is 0.16666666666666666
inverse of 7 is 0.14285714285714285
inverse of 8 is 0.125
inverse of 9 is 0.1111111111111111
inverse of 10 is 0.1


In [11]:
import numpy as np

In [12]:
k = np.array([[1,2,3],[1,2,3],[1,2,3]])
k

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [39]:
k = np.arange(1.0,26)
j = k.reshape(5,5)
j

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.],
       [ 16.,  17.,  18.,  19.,  20.],
       [ 21.,  22.,  23.,  24.,  25.]])

In [14]:
m = j.mean()
m

13.0

In [15]:
np.mean(j)

13.0

In [16]:
l = j.mean(0)
l

array([ 11.,  12.,  13.,  14.,  15.])

In [17]:
j.mean(0) #column wise mean 0 = vertical(column) 1 = horizontal(row wise) in numpy

array([ 11.,  12.,  13.,  14.,  15.])

In [18]:
j.mean(1)

array([  3.,   8.,  13.,  18.,  23.])

In [19]:
j.sum()

325.0

In [20]:
j.sum(0)

array([ 55.,  60.,  65.,  70.,  75.])

In [21]:
j.sum(1)

array([  15.,   40.,   65.,   90.,  115.])

In [22]:
k = np.arange(10)
j =k.reshape(5,2)
j

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [23]:
j.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [24]:
k=j.transpose()
j.shape

(5, 2)

In [25]:
np.dot(j,k)

array([[  1,   3,   5,   7,   9],
       [  3,  13,  23,  33,  43],
       [  5,  23,  41,  59,  77],
       [  7,  33,  59,  85, 111],
       [  9,  43,  77, 111, 145]])

In [26]:
np.arange(1,13).reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [27]:
np.arange(50).reshape(5,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [28]:
np.array([1,np.nan,np.nan])

array([  1.,  nan,  nan])

In [29]:
np.array([[1,np.nan,np.nan],[2,np.nan,np.nan]])

array([[  1.,  nan,  nan],
       [  2.,  nan,  nan]])

In [32]:
j[0:1,0:5]=[np.nan]  #nan works with float only so before changing values to nan change the type to float by astype 
j

array([[-2147483648, -2147483648],
       [          2,           3],
       [          4,           5],
       [          6,           7],
       [          8,           9]])

In [42]:
for i in range(5):
    j[i,i]=np.nan
    j

In [43]:
j

array([[ nan,   2.,   3.,   4.,   5.],
       [  6.,  nan,   8.,   9.,  10.],
       [ 11.,  12.,  nan,  14.,  15.],
       [ 16.,  17.,  18.,  nan,  20.],
       [ 21.,  22.,  23.,  24.,  nan]])

In [44]:
j

array([[ nan,   2.,   3.,   4.,   5.],
       [  6.,  nan,   8.,   9.,  10.],
       [ 11.,  12.,  nan,  14.,  15.],
       [ 16.,  17.,  18.,  nan,  20.],
       [ 21.,  22.,  23.,  24.,  nan]])

In [45]:
j[0:1]

array([[ nan,   2.,   3.,   4.,   5.]])

In [46]:
j[:,0]

array([ nan,   6.,  11.,  16.,  21.])

In [ ]:
j[0:1,1:4]

In [ ]:
j[1:3,1:3]

In [ ]:
j[3:,2:]

In [47]:
j = np.random.randint(20,51,5)
j

array([21, 26, 36, 34, 44])

In [49]:
from numpy.random import randint

In [50]:
j = randint(20,51,5)
j

array([44, 34, 21, 43, 35])

In [ ]:
k = randint(1,51,25)
j = k.reshape(5,5)
j

In [ ]:
np.random.random(5)

In [51]:
np.random.random(5)*10

array([ 8.66841493,  9.74958431,  0.74788804,  3.12959809,  1.46835992])

In [52]:
a = np.random.randn(10)
a

array([-0.1185277 , -1.06500596,  0.68583321, -1.10704441, -0.26590991,
       -0.11359689,  0.65732875,  0.08004118,  0.04834728,  1.20344007])

In [53]:
a.mean()

0.00049056273239915797

In [ ]:
from numpy.random import randn

In [ ]:
randn(10)

In [54]:
np.random.uniform(0,20,5)

array([ 11.55818001,   4.86325272,  10.76324373,   4.89449983,   3.48593893])

In [ ]:
randn(5,5)

In [55]:
a = randint(1,11,10)
a

array([10,  7,  5,  6,  4,  1,  2,  4, 10,  5])

In [56]:
b = randint(1,11,10)
b

array([6, 8, 5, 2, 2, 3, 1, 6, 6, 7])

In [57]:
np.maximum(a,b)

array([10,  8,  5,  6,  4,  3,  2,  6, 10,  7])

In [ ]:
a = np.array([1,2,3])
b= np.array([100,200,300])
c = np.array([True,False,True])

In [ ]:
np.where(c,a,b) #if c is true, it will return value from a ,else from b

In [ ]:
a = np.arange(4).reshape(2,2)
b= np.arange(2,6).reshape(2,2)
c = np.array([[True,False],[False,True]])
print(a)
print(b)
print(c)

In [ ]:
np.where(c,a,b)

In [59]:
arr1 = np.array([True, True, True])
arr2 = np.array([False, False,False])
arr3 = np.array([True,False,True])

In [60]:
arr1.any()   #if anyone is true, it will retuen true, else false

True

In [ ]:
arr2.any()

In [ ]:
arr3.any()

In [ ]:
arr1.all()  #if all are true, it will return true, else false

In [ ]:
arr2.all()

In [ ]:
arr3.all()

In [62]:
import pandas as pd

In [63]:
from pandas import Series

In [64]:
ser1 = Series([10,20,30,])
ser1

0    10
1    20
2    30
dtype: int64

In [65]:
ser2 = Series(['A','B','C'])
ser2

0    A
1    B
2    C
dtype: object

In [66]:
ser3 = Series([True,False,True])
ser3

0     True
1    False
2     True
dtype: bool

In [76]:
ser4 = Series([10,20,30],index=[44,99,40])
ser4

44    10
99    20
40    30
dtype: int64

In [72]:
ser5 = Series([1,2,3,4,5],index=['one','two','three','four','one'])
ser5

one      1
two      2
three    3
four     4
one      5
dtype: int64

In [68]:
ser6 = Series([10,20,30],index=[True,False,True])
ser6

True     10
False    20
True     30
dtype: int64

In [69]:
ser6[True]

True    10
True    30
dtype: int64

In [77]:
ser5['two']

2

In [78]:
ser4[40] #grab by index name

30

In [79]:
ser5[0] #grab by index position

1

In [80]:
ser5[1:3] #grab by index range

two      2
three    3
dtype: int64

In [81]:
ser5[['one','four']] #grab by multiple index name

one     1
one     5
four    4
dtype: int64

In [82]:
ser5[ser5>3] #grab by logic

four    4
one     5
dtype: int64

In [84]:
ser5>3

one      False
two      False
three    False
four      True
one       True
dtype: bool

In [83]:
ser5+5

one       6
two       7
three     8
four      9
one      10
dtype: int64

In [85]:
ser5[3] + 5

9

In [88]:
fb1 = Series(np.random.randint(1,11,10),index=list('abcdefghij'))
fb1



a    8
b    3
c    8
d    2
e    8
f    9
g    8
h    1
i    3
j    4
dtype: int32

In [89]:
fb1[['c','e','g']]=np.nan
fb1

a    8.0
b    3.0
c    NaN
d    2.0
e    NaN
f    9.0
g    NaN
h    1.0
i    3.0
j    4.0
dtype: float64

In [91]:
fb2 = Series(np.random.randint(1,11,10),index=list('abcdefghij'))
fb2

a     6
b     6
c    10
d     5
e     6
f    10
g     4
h     5
i     4
j     3
dtype: int32

In [92]:
fb2.index

Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

In [93]:
fb2.values

array([ 6,  6, 10,  5,  6, 10,  4,  5,  4,  3])

In [101]:
c=fb1.isnull()
c

a    False
b    False
c     True
d    False
e     True
f    False
g     True
h    False
i    False
j    False
dtype: bool

In [99]:
c=fb1.notnull()
c

a     True
b     True
c    False
d     True
e    False
f     True
g    False
h     True
i     True
j     True
dtype: bool

In [102]:
Series(np.where(c,fb2,fb1))

0     8.0
1     3.0
2    10.0
3     2.0
4     6.0
5     9.0
6     4.0
7     1.0
8     3.0
9     4.0
dtype: float64

In [103]:
fb11=Series(np.where(c,fb2,fb1),index=fb1.index)
fb11

a     8.0
b     3.0
c    10.0
d     2.0
e     6.0
f     9.0
g     4.0
h     1.0
i     3.0
j     4.0
dtype: float64

In [104]:
cfb= (fb11+fb2)/2
cfb

a     7.0
b     4.5
c    10.0
d     3.5
e     6.0
f     9.5
g     4.0
h     3.0
i     3.5
j     3.5
dtype: float64

In [105]:
math = Series(np.random.randint(0,101,5),index=['raj','shiv','chin','shin','mayi'])
math

raj      8
shiv    57
chin    87
shin    15
mayi    34
dtype: int32

In [106]:
science = Series(np.random.randint(0,101,5),index=['raj','shiv','chin','shin','mayi'])
science

raj     96
shiv     7
chin    99
shin    39
mayi    33
dtype: int32

In [107]:
math[['chin','mayi']]=np.nan
math

raj      8.0
shiv    57.0
chin     NaN
shin    15.0
mayi     NaN
dtype: float64

In [108]:
c=math.isnull()
c

raj     False
shiv    False
chin     True
shin    False
mayi     True
dtype: bool

In [110]:
math1 = Series(np.where(c,science,math),index=math.index)
total1 = (math1+science)/2
total1

raj     52.0
shiv    32.0
chin    99.0
shin    27.0
mayi    33.0
dtype: float64

# Dataframe 

In [111]:
a = Series({'a':'alpha','b':'beta'})
a

a    alpha
b     beta
dtype: object

dataframe is a tabular data structure of data which has rows and column in which data in the form of arrays which is very similar to csv and xls sheet

In [112]:
from pandas import Series,DataFrame

In [113]:
dframe1 = DataFrame(np.arange(25).reshape(5,5))
dframe1

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [114]:
dframe1 = DataFrame(np.arange(25).reshape(5,5),index = list('abcde'))
dframe1

0   1   2   3   4
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24

In [115]:
dframe1 = DataFrame(np.arange(25).reshape(5,5),index = list('abcde'), columns = ['col1','col2','col3','col4','col5'])
dframe1

col1  col2  col3  col4  col5
a     0     1     2     3     4
b     5     6     7     8     9
c    10    11    12    13    14
d    15    16    17    18    19
e    20    21    22    23    24

In [116]:
df1 = DataFrame({'names':['chin','mayi','shiv','raj'], 'weight':[89,100,200,369]})
df1

names  weight
0  chin      89
1  mayi     100
2  shiv     200
3   raj     369

In [117]:
df1 = DataFrame({'names':['chin','mayi','shiv','raj'], 'weight':[89,100,200,369]},index = list('abcd'))
df1

names  weight
a  chin      89
b  mayi     100
c  shiv     200
d   raj     369

In [163]:
df2 = DataFrame({'company':['wipro','cisco','google','infosys','tcs'],'price':[100,200,350,150,60], 
                 'ticker':['wip','cisc','goog','infy','tcs']})
df2

company  price ticker
0    wipro    100    wip
1    cisco    200   cisc
2   google    350   goog
3  infosys    150   infy
4      tcs     60    tcs

In [119]:
df2.columns

Index(['company', 'price', 'ticker'], dtype='object')

selecting entries in dataframes

In [120]:
df2['company'] #grab by column name

0      wipro
1      cisco
2     google
3    infosys
4        tcs
Name: company, dtype: object

In [121]:
df2[['company','price']] #grab by multiple column name

company  price
0    wipro    100
1    cisco    200
2   google    350
3  infosys    150
4      tcs     60

In [122]:
df2[df2['price']>150]  #grab by logic

company  price ticker
1   cisco    200   cisc
2  google    350   goog

In [151]:
df2['noe'] = 1000
df2

company  price ticker   noe
0    wipro    100    wip  1000
1    cisco    200   cisc  1000
2   google    350   goog  1000
3  infosys    150   infy  1000
4      tcs     60    tcs  1000

In [164]:
df2['noe'] = [1000,2000,500,200,600]
df2

company  price ticker   noe
0    wipro    100    wip  1000
1    cisco    200   cisc  2000
2   google    350   goog   500
3  infosys    150   infy   200
4      tcs     60    tcs   600

In [125]:
df2['noe'] = df2['noe']-50
df2

company  price ticker   noe
0    wipro    100    wip   950
1    cisco    200   cisc  1950
2   google    350   goog   450
3  infosys    150   infy   150
4      tcs     60    tcs   550

In [126]:
df2['dp'] = df2['price']-df2['price']*0.10
df2

company  price ticker   noe     dp
0    wipro    100    wip   950   90.0
1    cisco    200   cisc  1950  180.0
2   google    350   goog   450  315.0
3  infosys    150   infy   150  135.0
4      tcs     60    tcs   550   54.0

In [127]:
df2[1:3] #grab by range

company  price ticker   noe     dp
1   cisco    200   cisc  1950  180.0
2  google    350   goog   450  315.0

In [165]:
df2['haa']=np.nan
df2

company  price ticker   noe  haa
0    wipro    100    wip  1000  NaN
1    cisco    200   cisc  2000  NaN
2   google    350   goog   500  NaN
3  infosys    150   infy   200  NaN
4      tcs     60    tcs   600  NaN

In [149]:
df3 = DataFrame({'company':['wipro','cisco','google','infosys','tcs'],'price':[100,200,350,150,60], 
                 'ticker':['wip','cisc','goog','infy','tcs']},index= list('abcde'))
df3

company  price ticker
a    wipro    100    wip
b    cisco    200   cisc
c   google    350   goog
d  infosys    150   infy
e      tcs     60    tcs

In [ ]:
df3.ix['a']

# use of iloc

In [130]:
df2.iloc[2,:2]

company    google
price         350
Name: 2, dtype: object

In [131]:
df2.iloc[1,:3]

company    cisco
price        200
ticker      cisc
Name: 1, dtype: object

In [135]:
df2.iloc[1:4,:3]

company  price ticker
1    cisco    200   cisc
2   google    350   goog
3  infosys    150   infy

In [136]:
df2.iloc[:,1:2]

price
0    100
1    200
2    350
3    150
4     60

In [137]:
df2.iloc[1:3,0:2]

company  price
1   cisco    200
2  google    350

In [138]:
df3.loc['a']

company    wipro
price        100
ticker       wip
Name: a, dtype: object

In [139]:
df3.loc['a','price']

100

In [140]:
df3.loc['a','price':'ticker']

price     100
ticker    wip
Name: a, dtype: object

In [141]:
df3.loc['a',['price','ticker']]

price     100
ticker    wip
Name: a, dtype: object

In [142]:
df3.loc['a'][['price','ticker']]

price     100
ticker    wip
Name: a, dtype: object

# dropping entries in dataframes

In [166]:
g = df2
g

company  price ticker   noe  haa
0    wipro    100    wip  1000  NaN
1    cisco    200   cisc  2000  NaN
2   google    350   goog   500  NaN
3  infosys    150   infy   200  NaN
4      tcs     60    tcs   600  NaN

In [167]:
del g['ticker']  #changes original
g

company  price   noe  haa
0    wipro    100  1000  NaN
1    cisco    200  2000  NaN
2   google    350   500  NaN
3  infosys    150   200  NaN
4      tcs     60   600  NaN

In [168]:
df2.drop(1)  #doesnt change original

company  price   noe  haa
0    wipro    100  1000  NaN
2   google    350   500  NaN
3  infosys    150   200  NaN
4      tcs     60   600  NaN

In [159]:
df2

company  price   noe  haa
0    wipro    100  1000  NaN
1    cisco    200  2000  NaN
2   google    350   500  NaN
3  infosys    150   200  NaN
4      tcs     60   600  NaN

In [ ]:
df2.drop(1,inplace=True)  #changes original

In [ ]:
df2

In [172]:
df2.drop('company',axis=1)   #when there is same name in index and column

price   noe  haa
0    100  1000  NaN
1    200  2000  NaN
2    350   500  NaN
3    150   200  NaN
4     60   600  NaN

In [170]:
df2

company  price   noe  haa
0    wipro    100  1000  NaN
1    cisco    200  2000  NaN
2   google    350   500  NaN
3  infosys    150   200  NaN
4      tcs     60   600  NaN

In [173]:
abc = Series([1,2,3],index = list('abc'))
abc

a    1
b    2
c    3
dtype: int64

In [174]:
abc.drop('b')

a    1
c    3
dtype: int64

In [175]:
abc.reindex(list('xyz'))

x   NaN
y   NaN
z   NaN
dtype: float64

In [176]:
abc.reindex(list('abcxyz')) #chnages are not done to originals

a    1.0
b    2.0
c    3.0
x    NaN
y    NaN
z    NaN
dtype: float64

In [177]:
abc.reindex(list('abcxyz'),fill_value=0)

a    1
b    2
c    3
x    0
y    0
z    0
dtype: int64

In [178]:
acb= Series(['india','russia','bhutan'],index=[1,5,10])
acb

1      india
5     russia
10    bhutan
dtype: object

In [179]:
acb.reindex(range(15),method='ffill')

0        NaN
1      india
2      india
3      india
4      india
5     russia
6     russia
7     russia
8     russia
9     russia
10    bhutan
11    bhutan
12    bhutan
13    bhutan
14    bhutan
dtype: object

In [180]:
acb.reindex(range(15),method='bfill')

0      india
1      india
2     russia
3     russia
4     russia
5     russia
6     bhutan
7     bhutan
8     bhutan
9     bhutan
10    bhutan
11       NaN
12       NaN
13       NaN
14       NaN
dtype: object

In [181]:
acb.reindex(range(15),method='nearest')

0      india
1      india
2      india
3     russia
4     russia
5     russia
6     russia
7     russia
8     bhutan
9     bhutan
10    bhutan
11    bhutan
12    bhutan
13    bhutan
14    bhutan
dtype: object

# Sort

In [182]:
bbc = Series(np.random.randint(0,11,10),index=range(10))
bbc

0     2
1     6
2     8
3     8
4     6
5    10
6     9
7     2
8     0
9     9
dtype: int32

In [183]:
bbc1=bbc.sort_values()
bbc1

8     0
0     2
7     2
1     6
4     6
2     8
3     8
6     9
9     9
5    10
dtype: int32

In [184]:
bbc1.sort_index()

0     2
1     6
2     8
3     8
4     6
5    10
6     9
7     2
8     0
9     9
dtype: int32

In [185]:
bbc.sort_index(ascending=False)

9     9
8     0
7     2
6     9
5    10
4     6
3     8
2     8
1     6
0     2
dtype: int32

In [187]:
bbc.sort_index(ascending=False,inplace=True)
bbc

9     9
8     0
7     2
6     9
5    10
4     6
3     8
2     8
1     6
0     2
dtype: int32

In [188]:
tr=DataFrame({'Names':list('abcdef'),'math':np.random.randint(1,100,6),'science':np.random.randint(1,100,6)})
tr

Names  math  science
0     a    56       76
1     b    39       77
2     c    51        3
3     d    93       93
4     e    30       10
5     f    48       51

In [189]:
tr.sort_values (by = 'math')

Names  math  science
4     e    30       10
1     b    39       77
5     f    48       51
2     c    51        3
0     a    56       76
3     d    93       93

In [190]:
tr.sort_values (by = ['math','science'])

Names  math  science
4     e    30       10
1     b    39       77
5     f    48       51
2     c    51        3
0     a    56       76
3     d    93       93

In [191]:
tr.sort_values (by = ['math','science'],ascending=[True,False])

Names  math  science
4     e    30       10
1     b    39       77
5     f    48       51
2     c    51        3
0     a    56       76
3     d    93       93