In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from pandas import Series,DataFrame

In [67]:
ser1 = Series(['a','b','c','d','e','f','g','h','i','j'])

In [68]:
ser2 = Series(np.random.randint(1,100,10))

In [69]:
ser3 = Series(np.random.randint(1,100,10))

In [73]:
df = DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [74]:
df['names']=ser1

df['marks1']=ser2
df['marks2']=ser3
df

names  marks1  marks2
0     a       3      48
1     b      62      30
2     c      20      45
3     d      63      29
4     e       8      67
5     f      29       9
6     g      65       3
7     h      96      48
8     i      51      42
9     j      51      27

# RANK

In [76]:
df['rank']=df['marks1'].rank()
df

names  marks1  marks2  rank
0     a       3      48   1.0
1     b      62      30   7.0
2     c      20      45   3.0
3     d      63      29   8.0
4     e       8      67   2.0
5     f      29       9   4.0
6     g      65       3   9.0
7     h      96      48  10.0
8     i      51      42   5.5
9     j      51      27   5.5

In [77]:
df['rank']=df['marks1'].rank(ascending=0)
df

names  marks1  marks2  rank
0     a       3      48  10.0
1     b      62      30   4.0
2     c      20      45   8.0
3     d      63      29   3.0
4     e       8      67   9.0
5     f      29       9   7.0
6     g      65       3   2.0
7     h      96      48   1.0
8     i      51      42   5.5
9     j      51      27   5.5

In [78]:
df['rank']=df['marks1'].rank(ascending=1)
df

names  marks1  marks2  rank
0     a       3      48   1.0
1     b      62      30   7.0
2     c      20      45   3.0
3     d      63      29   8.0
4     e       8      67   2.0
5     f      29       9   4.0
6     g      65       3   9.0
7     h      96      48  10.0
8     i      51      42   5.5
9     j      51      27   5.5

In [79]:
df.iloc[1,1]=60
df

names  marks1  marks2  rank
0     a       3      48   1.0
1     b      60      30   7.0
2     c      20      45   3.0
3     d      63      29   8.0
4     e       8      67   2.0
5     f      29       9   4.0
6     g      65       3   9.0
7     h      96      48  10.0
8     i      51      42   5.5
9     j      51      27   5.5

In [80]:
df['rank min']= df['marks1'].rank(method='min')
df

names  marks1  marks2  rank  rank min
0     a       3      48   1.0       1.0
1     b      60      30   7.0       7.0
2     c      20      45   3.0       3.0
3     d      63      29   8.0       8.0
4     e       8      67   2.0       2.0
5     f      29       9   4.0       4.0
6     g      65       3   9.0       9.0
7     h      96      48  10.0      10.0
8     i      51      42   5.5       5.0
9     j      51      27   5.5       5.0

In [81]:
df['rank max']=df['marks1'].rank(ascending=False,method='max')
df

names  marks1  marks2  rank  rank min  rank max
0     a       3      48   1.0       1.0      10.0
1     b      60      30   7.0       7.0       4.0
2     c      20      45   3.0       3.0       8.0
3     d      63      29   8.0       8.0       3.0
4     e       8      67   2.0       2.0       9.0
5     f      29       9   4.0       4.0       7.0
6     g      65       3   9.0       9.0       2.0
7     h      96      48  10.0      10.0       1.0
8     i      51      42   5.5       5.0       6.0
9     j      51      27   5.5       5.0       6.0

In [84]:
df['rank dense']=df['marks1'].rank(ascending=False,method='dense')
df

names  marks1  marks2  rank  rank min  rank max  rank dense
0     a       3      48   1.0       1.0      10.0         9.0
1     b      60      30   7.0       7.0       4.0         4.0
2     c      20      45   3.0       3.0       8.0         7.0
3     d      63      29   8.0       8.0       3.0         3.0
4     e       8      67   2.0       2.0       9.0         8.0
5     f      29       9   4.0       4.0       7.0         6.0
6     g      65       3   9.0       9.0       2.0         2.0
7     h      96      48  10.0      10.0       1.0         1.0
8     i      51      42   5.5       5.0       6.0         5.0
9     j      51      27   5.5       5.0       6.0         5.0

# Index hierarchy

In [16]:
ser1=Series(np.arange(6),index=[['a','a','b','b','b','c'],[1,2,3,5,6,7]])
ser1

a  1    0
   2    1
b  3    2
   5    3
   6    4
c  7    5
dtype: int32

In [17]:
DataFrame(ser1)

0
a 1  0
  2  1
b 3  2
  5  3
  6  4
c 7  5

In [18]:
ser1.values

array([0, 1, 2, 3, 4, 5])

In [19]:
ser1.index

MultiIndex(levels=[['a', 'b', 'c'], [1, 2, 3, 5, 6, 7]],
           labels=[[0, 0, 1, 1, 1, 2], [0, 1, 2, 3, 4, 5]])

In [20]:
ser1['a']

1    0
2    1
dtype: int32

In [21]:
ser1['a'][2]

1

In [22]:
ser1['a',2]

1

In [23]:
ser1[:,1]

a    0
dtype: int32

In [24]:
df2 = DataFrame(np.arange(20).reshape(4,5),index=[['a','a','b','b'],[1,2,3,4]],
                columns=[['bangalore','bangalore','chennai','nagpur','nagpur'],['hot','cold','hot','windy','hot']])
df2

bangalore      chennai nagpur    
          hot cold     hot  windy hot
a 1         0    1       2      3   4
  2         5    6       7      8   9
b 3        10   11      12     13  14
  4        15   16      17     18  19

In [25]:
df2['bangalore','hot']

a  1     0
   2     5
b  3    10
   4    15
Name: (bangalore, hot), dtype: int32

In [26]:
df2.iloc[2]

bangalore  hot      10
           cold     11
chennai    hot      12
nagpur     windy    13
           hot      14
Name: (b, 3), dtype: int32

In [27]:
df2.loc['b',3]['nagpur','windy']

13

In [28]:
df2.swaplevel(0)

bangalore      chennai nagpur    
          hot cold     hot  windy hot
1 a         0    1       2      3   4
2 a         5    6       7      8   9
3 b        10   11      12     13  14
4 b        15   16      17     18  19

In [29]:
df2.swaplevel(0,axis=1)

hot      cold     hot  windy    hot
    bangalore bangalore chennai nagpur nagpur
a 1         0         1       2      3      4
  2         5         6       7      8      9
b 3        10        11      12     13     14
  4        15        16      17     18     19

In [30]:
df2.index.names = ['p','c']
df2.columns.names = ['cities','weather']
df2

cities  bangalore      chennai nagpur    
weather       hot cold     hot  windy hot
p c                                      
a 1             0    1       2      3   4
  2             5    6       7      8   9
b 3            10   11      12     13  14
  4            15   16      17     18  19

In [31]:
df2.sort_index(axis=1)

cities  bangalore     chennai nagpur      
weather      cold hot     hot    hot windy
p c                                       
a 1             1   0       2      4     3
  2             6   5       7      9     8
b 3            11  10      12     14    13
  4            16  15      17     19    18

In [32]:
df3=DataFrame(np.random.randint(1,100,20).reshape(4,5),index=[['3','3','2','2'],[1,2,1,2]],
                                   columns=[['3','3','9','5','5'],
                                               ['1','4','8','2','6']])
df3

3       9   5    
      1   4   8   2   6
3 1  32  35  37  90  17
  2  12  30  53  79  86
2 1  19   8  78  24  12
  2  59   2  45  41  25

In [33]:
ser=Series((1,2,np.nan,4,np.nan))
ser

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
dtype: float64

In [34]:
ser.isnull()


0    False
1    False
2     True
3    False
4     True
dtype: bool

In [35]:
ser.notnull()

0     True
1     True
2    False
3     True
4    False
dtype: bool

In [36]:
ser.isnull().sum()

2

In [37]:
ser.dropna()

0    1.0
1    2.0
3    4.0
dtype: float64

In [38]:
df4 = DataFrame(np.array([[1,2,3],[np.nan,5,6],[7,np.nan,9],[np.nan,np.nan,np.nan]]))
df4

0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  NaN  9.0
3  NaN  NaN  NaN

In [39]:
df4.dropna()

0    1    2
0  1.0  2.0  3.0

In [40]:
df4.dropna(how='any')

0    1    2
0  1.0  2.0  3.0

In [41]:
df4.dropna(how='any',axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [42]:
df4.dropna(how='all')

0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  NaN  9.0

In [43]:
df4.dropna(thresh=1)

0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  NaN  9.0

In [44]:
df4.dropna(thresh=2)

0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  NaN  9.0

In [45]:
df4.dropna(thresh=3)

0    1    2
0  1.0  2.0  3.0

In [46]:
df4.fillna(0)

0    1    2
0  1.0  2.0  3.0
1  0.0  5.0  6.0
2  7.0  0.0  9.0
3  0.0  0.0  0.0

In [47]:
df4[1].fillna(0,inplace = True)

In [48]:
df4

0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  0.0  9.0
3  NaN  0.0  NaN

In [49]:
df4.ffill()

0    1    2
0  1.0  2.0  3.0
1  1.0  5.0  6.0
2  7.0  0.0  9.0
3  7.0  0.0  9.0

In [50]:
df4.bfill()

0    1    2
0  1.0  2.0  3.0
1  7.0  5.0  6.0
2  7.0  0.0  9.0
3  NaN  0.0  NaN

In [51]:
df4.ffill(axis=1)

0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  0.0  9.0
3  NaN  0.0  0.0

In [52]:
df4.bfill(axis=0)

0    1    2
0  1.0  2.0  3.0
1  7.0  5.0  6.0
2  7.0  0.0  9.0
3  NaN  0.0  NaN

In [53]:
df4

0    1    2
0  1.0  2.0  3.0
1  NaN  5.0  6.0
2  7.0  0.0  9.0
3  NaN  0.0  NaN

# Replacement

In [54]:
ser = Series([1,2,3,4,1,2,3,4])
ser

0    1
1    2
2    3
3    4
4    1
5    2
6    3
7    4
dtype: int64

In [55]:
ser.replace([1,4],[100,400])

0    100
1      2
2      3
3    400
4    100
5      2
6      3
7    400
dtype: int64

In [56]:
ser.replace({1:100,2:600})

0    100
1    600
2      3
3      4
4    100
5    600
6      3
7      4
dtype: int64

# Rename Index

In [14]:
import numpy as np

In [15]:
df6= DataFrame(np.arange(12).reshape(3,4),index=['ny','la','sf'],columns=list('abcd'))
df6

a  b   c   d
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [58]:
df6.rename({'ny':'new york'})

a  b   c   d
new york  0  1   2   3
la        4  5   6   7
sf        8  9  10  11

In [17]:
df6.rename({'a':'alpha'},axis=1)

a  b   c   d
ny  0  1   2   3
la  4  5   6   7
sf  8  9  10  11

In [87]:
df6.rename(index={'la':'los'},columns={'b':'beta'})

a  beta   c   d
ny   0     1   2   3
los  4     5   6   7
sf   8     9  10  11

# Duplicates

In [88]:
df7=DataFrame({'key1':['a','a','a','b','b'],'key2':[2,2,3,3,3]})
df7

key1  key2
0    a     2
1    a     2
2    a     3
3    b     3
4    b     3

In [89]:
df7.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [91]:
df7.duplicated(['key1'])

0    False
1     True
2     True
3    False
4     True
dtype: bool

In [92]:
df7.duplicated(['key1'],keep='last')

0     True
1     True
2    False
3     True
4    False
dtype: bool

In [93]:
df7.drop_duplicates()

key1  key2
0    a     2
2    a     3
3    b     3

In [94]:
df7.drop_duplicates(keep='last')

key1  key2
1    a     2
2    a     3
4    b     3

In [95]:
df7.drop_duplicates(['key1'],keep='last')

key1  key2
2    a     3
4    b     3

In [2]:
import pandas as pd
from pandas import DataFrame,Series

In [12]:
#mapping
df3 = DataFrame({'name':['shiv','chin','raj'],'weight':[300,5000,800]})
height = {'raj':160,'shiv':200,'chin':300}
df3['height']=df3['name'].map(height)
df3

name  weight  height
0  shiv     300     200
1  chin    5000     300
2   raj     800     160

In [97]:
#concatenate
arr1=np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
np.concatenate([arr1,arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [99]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [100]:
ser1 = Series([10,20,30],index=list('tuv'))
ser1

t    10
u    20
v    30
dtype: int64

In [101]:
ser2 = Series([40,50],index=list('xy'))
ser2

x    40
y    50
dtype: int64

In [102]:
pd.concat([ser1,ser2])

t    10
u    20
v    30
x    40
y    50
dtype: int64

# Combining

In [103]:
ser3 = Series([1,np.nan,2,np.nan,3,np.nan],index=list('pqrstu'))
ser4 = Series([10,20,30,40,50,60],index=list('pqrstu'))
ser3.combine_first(ser4)

p     1.0
q    20.0
r     2.0
s    40.0
t     3.0
u    60.0
dtype: float64

# Pivot

In [104]:
df = DataFrame({'Data':[1,2,3,1,2,3,1,2,3],'Variable':['a','a','a','b','b','b','c','c','c'],'value':np.random.randn(9)})
df

Data Variable     value
0     1        a  0.742292
1     2        a  1.055373
2     3        a  0.145857
3     1        b  1.269935
4     2        b -0.180174
5     3        b  0.666299
6     1        c -0.590217
7     2        c -1.468834
8     3        c  0.993315

In [105]:
df.pivot('Data','Variable','value')

Variable         a         b         c
Data                                  
1         0.742292  1.269935 -0.590217
2         1.055373 -0.180174 -1.468834
3         0.145857  0.666299  0.993315

In [106]:
df.pivot('Variable','Data','value')

Data             1         2         3
Variable                              
a         0.742292  1.055373  0.145857
b         1.269935 -0.180174  0.666299
c        -0.590217 -1.468834  0.993315

In [107]:
df.pivot('value','Variable','Data')

Variable     a    b    c
value                   
-1.468834  NaN  NaN  2.0
-0.590217  NaN  NaN  1.0
-0.180174  NaN  2.0  NaN
 0.145857  3.0  NaN  NaN
 0.666299  NaN  3.0  NaN
 0.742292  1.0  NaN  NaN
 0.993315  NaN  NaN  3.0
 1.055373  2.0  NaN  NaN
 1.269935  NaN  1.0  NaN

In [108]:
df.describe()

Data     value
count  9.000000  9.000000
mean   2.000000  0.292650
std    0.866025  0.901176
min    1.000000 -1.468834
25%    1.000000 -0.180174
50%    2.000000  0.666299
75%    3.000000  0.993315
max    3.000000  1.269935

In [ ]:
df

# Merge

In [119]:
df = DataFrame({'data1':np.arange(6),'key':list('xzyzxx')})
df

data1 key
0      0   x
1      1   z
2      2   y
3      3   z
4      4   x
5      5   x

In [120]:
df1 = DataFrame({'data2':np.arange(1,4),'key':list('qyz')})
df1

data2 key
0      1   q
1      2   y
2      3   z

In [121]:
pd.merge(df,df1)

data1 key  data2
0      1   z      3
1      3   z      3
2      2   y      2

In [112]:
pd.merge(df,df1,how='inner',on='key')

data1 key  data2
0      1   z      3
1      3   z      3
2      2   y      2

In [113]:
pd.merge(df,df1,how='outer',on='key')

data1 key  data2
0    0.0   x    NaN
1    4.0   x    NaN
2    5.0   x    NaN
3    1.0   z    3.0
4    3.0   z    3.0
5    2.0   y    2.0
6    NaN   q    1.0

In [114]:
pd.merge(df,df1,how='left',on='key')

data1 key  data2
0      0   x    NaN
1      1   z    3.0
2      2   y    2.0
3      3   z    3.0
4      4   x    NaN
5      5   x    NaN

In [115]:
pd.merge(df,df1,how='right',on='key')

data1 key  data2
0    1.0   z      3
1    3.0   z      3
2    2.0   y      2
3    NaN   q      1

# Type 2 column and index merge

In [116]:
df = DataFrame({'data1':np.arange(1,6),'key':list('xxyyz')})
df1 = DataFrame({'group data':[10,20]},index=['x','x'])
df1

group data
x          10
x          20

In [117]:
df

data1 key
0      1   x
1      2   x
2      3   y
3      4   y
4      5   z

In [ ]:
pd.merge(df,df1,left_on='key',right_index=True)

In [ ]:
pd.merge(df1,df,left_index=True,right_on='key')

In [ ]:
df2 = DataFrame({'data':[2,3,4,5]},index=['x','y','x','z'])

In [ ]:
pd.merge(df1,df2,left_index=True,right_index=True)